// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyDy4mvwgr3nh_KvGC3StiuRYnhxmIRoADA',
  appId: '1:587647188305:web:b3ee55583003205b8c6770',
  messagingSenderId: '587647188305',
  projectId: 'tutor-finding-598cc',
  authDomain: 'tutor-finding-598cc.firebaseapp.com',
  storageBucket: 'tutor-finding-598cc.firebasestorage.app',
  measurementId: 'G-7N9TL137B5',
  // Remove this line - it's for Realtime Database, not needed for Auth/Firestore
  // databaseURL: 'https://tutor-finding-598cc-default-rtdb.firebaseio.com',
);

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OZ0nPeDdPAIlALRGXq09KntjZIQ_0ek',
    appId: '1:587647188305:android:b3e8e401d63e3c718c6770',
    messagingSenderId: '587647188305',
    projectId: 'tutor-finding-598cc',
    storageBucket: 'tutor-finding-598cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4m14C8uQt-H3oASJ0cX_a6rkKqJCe8iQ',
    appId: '1:587647188305:ios:10abe2a52e71fcc98c6770',
    messagingSenderId: '587647188305',
    projectId: 'tutor-finding-598cc',
    storageBucket: 'tutor-finding-598cc.firebasestorage.app',
    iosBundleId: 'com.example.tutorFinding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4m14C8uQt-H3oASJ0cX_a6rkKqJCe8iQ',
    appId: '1:587647188305:ios:10abe2a52e71fcc98c6770',
    messagingSenderId: '587647188305',
    projectId: 'tutor-finding-598cc',
    storageBucket: 'tutor-finding-598cc.firebasestorage.app',
    iosBundleId: 'com.example.tutorFinding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy4mvwgr3nh_KvGC3StiuRYnhxmIRoADA',
    appId: '1:587647188305:web:20785788345693e28c6770',
    messagingSenderId: '587647188305',
    projectId: 'tutor-finding-598cc',
    authDomain: 'tutor-finding-598cc.firebaseapp.com',
    storageBucket: 'tutor-finding-598cc.firebasestorage.app',
    measurementId: 'G-XH54JK1D8F',
  );
}
